import { Header } from "../../components/layout/Header";
import "../../styles/globals.css";
import Head from "../head";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head />
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
